include(
    ":app",
    ":domain",
    ":libraries:rest-omdb",
    ":libraries:persistance",
    ":libraries:ui-components",
    ":libraries:actions",
    ":libraries:unidirectional-dataflow",
    ":libraries:coroutines-testutils",
    ":features:onboarding",
    ":features:home",
    ":features:details",
    ":features:favorites"
)