# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Output configuration for debugging"
  lane :config do
    puts is_ci
    sh("fastlane --version")
    gradle(task: "--version")
    sh("fastlane lanes")
    gradle(task: "tasks")
    gradle(task: "model")
    gradle(task: "projects")
    gradle(task: "properties")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
end
