name: Android CI

# Execute Push Pipeline on push to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  ##########################################################
  # Compile Job:
  # Install dependencies and compile debug and test sources
  ##########################################################
  compile:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Cache Bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run Fastlane Compile Lane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'compile'
          bundle-install-path: 'vendor/bundle'

  ##########################################################
  # Lint Job:
  # Install dependencies and execute analysis debug
  ##########################################################
  analysis:
    needs: compile
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Cache Bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run Fastlane Compile Analysis
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'analysis'
          bundle-install-path: 'vendor/bundle'

  ##########################################################
  # Unit Test Job:
  # Install dependencies and execute unit tests
  ##########################################################
  unit_test:
    needs: analysis
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Cache Bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run Fastlane Compile Analysis
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'unit_test'
          bundle-install-path: 'vendor/bundle'

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
