name: Android CI

# Execute Push Pipeline on push to master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  ##########################################################
  # Static Analysis Job
  ##########################################################
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.2

      - name: Compute key for CI cache
        run: ./compute-ci-cache-key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.1
        with:
          java-version: 1.8

      - name: Check code formatting
        run: ./gradlew ktlintCheck --stacktrace

      - name: Check code smells
        run: ./gradlew detekt --stacktrace

  ##########################################################
  # Unit Test Job
  ##########################################################
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.2

      - name: Compute key for CI cache
        run: ./compute-ci-cache-key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.1
        with:
          java-version: 1.8

      - name: Run unit tests and capture code coverage
        run: ./gradlew clean jacocoTestReport jacocoTestReportDebug --stacktrace

      - name: Share test reports with Codecov
        uses: codecov/codecov-action@v1.0.13

  ##########################################################
  # Assemble Job
  ##########################################################
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.2

      - name: Compute key for CI cache
        run: ./compute-ci-cache-key.sh key.txt

      - name: Setup cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('key.txt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1.4.1
        with:
          java-version: 1.8

      - name: Assemble APK
        run: ./gradlew clean assembleDebug --stacktrace


  #     Codecov container action is only supported on Linux
  #      - name: Run codacy coverage reports
  #        uses: codacy/codacy-coverage-reporter-action@master
  #        with:
  #          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
