name: Android CI

# Execute Push Pipeline on push to master
on: [push]

jobs:
  ##########################################################
  # Compile Job:
  # Install dependencies and compile debug and test sources
  ##########################################################
  compile:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane Compile Lane
        run: fastlane compile

  ##########################################################
  # Lint Job:
  # Install dependencies and execute analysis debug
  ##########################################################
  analysis:
    needs: compile
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane Analysis Lane
        run: fastlane analysis

  ##########################################################
  # Assemble Job:
  # Install dependencies and assemble debug and test APKs
  ##########################################################
  assemble:
    needs: analysis
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane Assemble Lane
        run: fastlane assemble

  ##########################################################
  # Unit Test Job:
  # Install dependencies and execute unit tests
  ##########################################################
  unit_test:
    needs: assemble
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane Unit Test Lane
        run: fastlane unit_test

  ##########################################################
  # Instrumentation Test Job:
  # Install dependencies and execute instrumentation tests
  # - Using macOS to initiate Android Emulator
  ##########################################################
  instrumentation_test:
    needs: assemble
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Instrumentation Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew connectedDebugAndroidTest

#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build with Gradle
#        run: ./gradlew clean build jacocoTestReport assembleAndroidTest coveralls --stacktrace
